import AboutUs from "@/components/AboutUs";
import MainHeader from "@/components/MainHeader";
import Team from "@/components/Team";
import Testimonial from "@/components/Testimonial";
import Contact from "@/components/contact";
import Head from "next/head";
// import "./globals.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainHeader />
      <AboutUs />
      <Team />
      <Testimonial />
      <Contact />
    </>
  );
}
